### ISSUE TITLE
Chi Squared CDF for large degrees of freedom returns NaN

### ISSUE THREAD

**Issue by bbieniek** [mathnet/mathnet-numerics#288]
In order to compute the CDF for Chi Squared distribution, you call a method:
SpecialFunctions.GammaLowerIncomplete(freedom/2.0, x/2.0)/SpecialFunctions.Gamma(freedom/2.0);

The SpecialFunctions.GammaLowerIncomplete method uses:
public static double GammaLowerIncomplete(double a, double x)
        {
            return GammaLowerRegularized(a, x)*Gamma(a);
        }

So, in fact you're calling the Gamma method twice. Once to to multiply and the second to divide a value returned from GammaLowerRegularized.

I noticed that for large degrees of freedom (19000), the Gamma function returns NaN/Infinity.
I think it would be better to call the GammaLowerRegularized from CDF method to avoid multiplication and division, which is not numerically safe.

**Comment by bbieniek** [comment]
This was fixed in my branch: https://github.com/bbieniek/mathnet-numerics/commit/e0e7292324604478142c2596507b45967e65244a

**Comment by cdrnet** [comment]
Thanks for the analysis and the fix!

Could you open a pull request?

**Comment by bbieniek** [comment]
https://github.com/mathnet/mathnet-numerics/pull/289

**Comment by cdrnet** [comment]
Thanks. I noticed the change will currently break 4 unit tests (see AppVeyor build), but it looks like this may actually be test bugs.

**Comment by bbieniek** [comment]
3 tests expected NaNs as a result of a call to CDF.
I compared the test results with R:

00:12:42] Tests run: 19368, Errors: 0, Failures: 4, Inconclusive: 1260, Time: 31.648646 seconds
[00:12:42]   Not run: 35, Invalid: 0, Ignored: 35, Skipped: 0
[00:12:42] 
[00:12:42] Errors and Failures:
[00:12:42] 1) Test Failure : MathNet.Numerics.UnitTests.DistributionTests.Continuous.ChiSquareTests.ValidateCumulativeDistribution(double.PositiveInfinity,0.0d)
[00:12:42]      Expected: NaN
[00:12:42]   But was:  0.0d
[00:12:42] 
[00:12:42] at MathNet.Numerics.UnitTests.DistributionTests.Continuous.ChiSquareTests.ValidateCumulativeDistribution(Double dof, Double x) in c:\projects\mathnet-numerics\src\UnitTests\DistributionTests\Continuous\ChiSquareTests.cs:line 325
[00:12:42] 
[00:12:42] 2) Test Failure : MathNet.Numerics.UnitTests.DistributionTests.Continuous.ChiSquareTests.ValidateCumulativeDistribution(double.PositiveInfinity,0.1d)
[00:12:42]      Expected: NaN
[00:12:42]   But was:  0.0d
[00:12:42] 
[00:12:42] at MathNet.Numerics.UnitTests.DistributionTests.Continuous.ChiSquareTests.ValidateCumulativeDistribution(Double dof, Double x) in c:\projects\mathnet-numerics\src\UnitTests\DistributionTests\Continuous\ChiSquareTests.cs:line 325
[00:12:42] 
[00:12:42] 3) Test Failure : MathNet.Numerics.UnitTests.DistributionTests.Continuous.ChiSquareTests.ValidateCumulativeDistribution(double.PositiveInfinity,1.0d)
[00:12:42]      Expected: NaN
[00:12:42]   But was:  0.0d
[00:12:42] 
[00:12:42] at MathNet.Numerics.UnitTests.DistributionTests.Continuous.ChiSquareTests.ValidateCumulativeDistribution(Double dof, Double x) in c:\projects\mathnet-numerics\src\UnitTests\DistributionTests\Continuous\ChiSquareTests.cs:line 325

![image](https://cloud.githubusercontent.com/assets/10694177/6231619/29daa0ec-b6c7-11e4-8943-7af8361e955f.png)

Both function and R are giving the same results now.

One test is off:
[00:12:42]   Expected: 0.68268949213708585d
[00:12:42]   But was:     0.68268949213708596d

This is probably a result of lack of division and multiplication.

**Comment by cdrnet** [comment]
I just realized that the failing unit test does not make much sense at all. We effectively compare our own implementation against itself instead of to a reference computed externally. I'll have to fix the test first before I can pull your fix.

**Comment by cdrnet** [comment]
I've finally updated the tests and merged - thanks again!
