### ISSUE TITLE
Gamma.InvCDF bug

### ISSUE THREAD

**Issue by marikhub** [mathnet/mathnet-numerics#553]
double param1 = 3698900.3198200003;
double param2 = 0.05989802133984444;
double x = 0.99994525127112865;
Gamma.InvCDF(param1, param2, x);

When I try this parameters for gamma inverse CDF I am receiving following error:
"Value must not be negative (zero is ok).\r\nParameter name : x".
But when I reduce x value to 15 digits after comma it seems to work.

**Comment by RelativelyRandom** [comment]
I had the same exception when calling ChiSquared.InvCDF(31115, 0.999). Looking at the stack trace, looks like it might be the exact same bug?

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Value must not be negative (zero is ok).
Parameter name: x
  Source=MathNet.Numerics
  StackTrace:
   at MathNet.Numerics.SpecialFunctions.GammaLowerRegularized(Double a, Double x)
   at MathNet.Numerics.SpecialFunctions.GammaLowerRegularizedInv(Double a, Double y0)
   at MathNet.Numerics.Distributions.ChiSquared.InvCDF(Double freedom, Double p)
   at .........
